import { Group } from 'src/app/interaces/Group';
import { groupLeaders } from './LeaderCatalog';
import { fullGroupMembers } from './GroupMember';
import { groupMembers } from './MemberCatalog';

export const groups: Group[] = [
    {
        groupName: "Charter Oak Savers",
        groupLocation: "Hartford, CT",
        payoutSystem: "EPS",
        savingsTarget: 10000,
        groupSize: 10,
        startDate: new Date('2024-01-01'),
        contribution: 500,
        frequency: 'Bi',
        nextContribution: new Date('2024-02-01'),
        endDate: new Date('2024-12-01'),
        isActive: true,
        groupMembers: fullGroupMembers,
        groupLeader: groupLeaders[0],
        minReputationScore: 92,
        cycle: 3
      },
      {
        groupName: "Elm City Network",
        groupLocation: "Hartford, CT",
        payoutSystem: "ECPS",
        savingsTarget: 15000,
        groupSize: 15,
        startDate: new Date('2024-03-01'),
        contribution: 1000,
        frequency: 'Mo',
        nextContribution: new Date('2024-04-01'),
        endDate: new Date('2025-03-01'),
        isActive: true,
        groupMembers: groupMembers[0],
        groupLeader: groupLeaders[1],
        minReputationScore: 90,
        cycle: 2
      },
      {
        groupName: "New Haven Trust",
        groupLocation: "New Haven, CT",
        payoutSystem: "EPS",
        savingsTarget: 8000,
        groupSize: 8,
        startDate: new Date('2024-02-01'),
        contribution: 400,
        frequency: 'Bi',
        nextContribution: new Date('2024-03-01'),
        endDate: new Date('2024-11-01'),
        isActive: true,
        groupMembers: groupMembers[1],
        groupLeader: groupLeaders[2],
        minReputationScore: 82,
        cycle: 1
      },
    {
      groupName: "Bluegrass Savers",
      groupLocation: "Lexington, KY",
      payoutSystem: "EPS",
      savingsTarget: 12000,
      groupSize: 12,
      startDate: new Date('2024-02-15'),
      contribution: 400,
      frequency: 'Bi',
      nextContribution: new Date('2024-03-15'),
      endDate: new Date('2024-12-15'),
      isActive: true,
      groupMembers: groupMembers[2],
      groupLeader: groupLeaders[3],
      minReputationScore: 75,
      cycle: 1
    },
    {
      groupName: "Lexington Legends",
      groupLocation: "Lexington, KY",
      payoutSystem: "ECPS",
      savingsTarget: 20000,
      groupSize: 20,
      startDate: new Date('2024-04-01'),
      contribution: 1000,
      frequency: 'Mo',
      nextContribution: new Date('2024-05-01'),
      endDate: new Date('2024-12-01'),
      isActive: true,
      groupMembers: groupMembers[3],
      groupLeader: groupLeaders[4],
      minReputationScore: 95,
      cycle: 2
    },
    {
      groupName: "Kentucky Pioneers",
      groupLocation: "Lexington, KY",
      payoutSystem: "ECPS",
      savingsTarget: 15000,
      groupSize: 10,
      startDate: new Date('2024-01-20'),
      contribution: 750,
      frequency: 'Bi',
      nextContribution: new Date('2024-02-20'),
      endDate: new Date('2024-11-20'),
      isActive: true,
      groupMembers: groupMembers[4],
      groupLeader: groupLeaders[5],
      minReputationScore: 75,
      cycle: 1
    },
    {
      groupName: "Dallas Dreamers",
      groupLocation: "Dallas, TX",
      payoutSystem: "EPS",
      savingsTarget: 12000,
      groupSize: 12,
      startDate: new Date('2024-01-10'),
      contribution: 1000,
      frequency: 'Bi',
      nextContribution: new Date('2024-02-10'),
      endDate: new Date('2024-11-10'),
      isActive: true,
      groupMembers: groupMembers[5],
      groupLeader: groupLeaders[6],
      minReputationScore: 95,
      cycle: 3
    },
    {
      groupName: "Lone Star Savers",
      groupLocation: "Dallas, TX",
      payoutSystem: "ECPS",
      savingsTarget: 10000,
      groupSize: 10,
      startDate: new Date('2024-02-01'),
      contribution: 500,
      frequency: 'Bi',
      nextContribution: new Date('2024-03-01'),
      endDate: new Date('2024-12-01'),
      isActive: true,
      groupMembers: groupMembers[6],
      groupLeader: groupLeaders[7],
      minReputationScore: 75,
      cycle: 1
    },
    {
      groupName: "Texan Treasurers",
      groupLocation: "Dallas, TX",
      payoutSystem: "EPS",
      savingsTarget: 9500,
      groupSize: 9,
      startDate: new Date('2024-03-15'),
      contribution: 530,
      frequency: 'Bi',
      nextContribution: new Date('2024-04-15'),
      endDate: new Date('2024-12-15'),
      isActive: true,
      groupMembers: groupMembers[7],
      groupLeader: groupLeaders[8],
      minReputationScore: 82,
      cycle: 1
    },
    {
      groupName: "Big Apple Savers",
      groupLocation: "New York, NY",
      payoutSystem: "EPS",
      savingsTarget: 13000,
      groupSize: 13,
      startDate: new Date('2024-03-01'),
      contribution: 1000,
      frequency: 'Mo',
      nextContribution: new Date('2024-04-01'),
      endDate: new Date('2024-12-01'),
      isActive: true,
      groupMembers: groupMembers[8],
      groupLeader: groupLeaders[9],
      minReputationScore: 98,
      cycle: 2
    },
    {
      groupName: "Empire State Investors",
      groupLocation: "New York, NY",
      payoutSystem: "ECPS",
      savingsTarget: 12000,
      groupSize: 12,
      startDate: new Date('2024-04-15'),
      contribution: 1000,
      frequency: 'Bi',
      nextContribution: new Date('2024-05-15'),
      endDate: new Date('2025-01-15'),
      isActive: true,
      groupMembers: groupMembers[9],
      groupLeader: groupLeaders[10],
      minReputationScore: 98,
      cycle: 1
    },
    {
      groupName: "NYC Finance Circle",
      groupLocation: "New York, NY",
      payoutSystem: "EPS",
      savingsTarget: 15000,
      groupSize: 15,
      startDate: new Date('2024-02-01'),
      contribution: 500,
      frequency: 'Bi',
      nextContribution: new Date('2024-03-01'),
      endDate: new Date('2024-11-01'),
      isActive: true,
      groupMembers: groupMembers[10],
      groupLeader: groupLeaders[11],
      minReputationScore: 92,
      cycle: 2
    },
    {
      groupName: "Tampa Bay Trust",
      groupLocation: "Tampa, FL",
      payoutSystem: "EPS",
      savingsTarget: 10500,
      groupSize: 10,
      startDate: new Date('2024-01-05'),
      contribution: 525,
      frequency: 'Bi',
      nextContribution: new Date('2024-02-05'),
      endDate: new Date('2024-11-05'),
      isActive: true,
      groupMembers: groupMembers[11],
      groupLeader: groupLeaders[12],
      minReputationScore: 80,
      cycle: 2
    },
    {
      groupName: "Florida Finance Guild",
      groupLocation: "Tampa, FL",
      payoutSystem: "ECPS",
      savingsTarget: 9500,
      groupSize: 9,
      startDate: new Date('2024-02-20'),
      contribution: 500,
      frequency: 'Bi',
      nextContribution: new Date('2024-03-20'),
      endDate: new Date('2024-11-20'),
      isActive: true,
      groupMembers: groupMembers[12],
      groupLeader: groupLeaders[13],
      minReputationScore: 70,
      cycle: 1
    },
    {
      groupName: "Sunshine Savers",
      groupLocation: "Tampa, FL",
      payoutSystem: "EPS",
      savingsTarget: 12000,
      groupSize: 12,
      startDate: new Date('2024-03-10'),
      contribution: 1000,
      frequency: 'Mo',
      nextContribution: new Date('2024-04-10'),
      endDate: new Date('2024-12-10'),
      isActive: true,
      groupMembers: groupMembers[13],
      groupLeader: groupLeaders[14],
      minReputationScore: 95,
      cycle: 2
    }
];
